// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKYpXzkyYM-td4pQVzjj72jN0PDMwr8rA',
    appId: '1:235029167979:web:c2129df9998021b01f962e',
    messagingSenderId: '235029167979',
    projectId: 'fir-auth-cab3a',
    authDomain: 'fir-auth-cab3a.firebaseapp.com',
    storageBucket: 'fir-auth-cab3a.appspot.com',
    measurementId: 'G-YYM23EMX4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCDSAYIQFo0UXnwuWArUQkHGmmCuskz8I',
    appId: '1:235029167979:android:8c705e7698fb70611f962e',
    messagingSenderId: '235029167979',
    projectId: 'fir-auth-cab3a',
    storageBucket: 'fir-auth-cab3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPaoNXFrkjZSvrNjBCY-DCaZrUNgTNxRQ',
    appId: '1:235029167979:ios:834a2a0313255bbf1f962e',
    messagingSenderId: '235029167979',
    projectId: 'fir-auth-cab3a',
    storageBucket: 'fir-auth-cab3a.appspot.com',
    iosClientId: '235029167979-2oku5okn1tirfmh003t66v7pvsaimae5.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPaoNXFrkjZSvrNjBCY-DCaZrUNgTNxRQ',
    appId: '1:235029167979:ios:b2bcc0dc02e09a831f962e',
    messagingSenderId: '235029167979',
    projectId: 'fir-auth-cab3a',
    storageBucket: 'fir-auth-cab3a.appspot.com',
    iosClientId: '235029167979-fd7p29dc0geo8jabgp1qd922u4i2u225.apps.googleusercontent.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
